# Generated by Django 5.0.6 on 2024-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPost',
            fields=[
                ('enagement_post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField()),
                ('number_of_likes', models.BigIntegerField(blank=True, null=True)),
                ('number_of_shares', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('customer_interaction_date', models.DateTimeField(blank=True, null=True)),
                ('shopping_url', models.CharField(blank=True, max_length=100, null=True)),
                ('customers_who_liked', models.TextField(blank=True, null=True)),
                ('content_type', models.IntegerField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cancelled', models.BooleanField()),
                ('schedule_code', models.CharField(blank=True, max_length=50, null=True)),
                ('button_cta', models.CharField(blank=True, max_length=20, null=True)),
                ('is_new_collection', models.BooleanField(blank=True, null=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('is_multihost', models.BooleanField(blank=True, null=True)),
                ('disabled_product', models.BooleanField(blank=True, null=True)),
                ('cta_url', models.TextField(blank=True, null=True)),
                ('product_thumbnail_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engagement_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementPostContent',
            fields=[
                ('engagement_post_content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engagement_post_content',
                'db_table_comment': 'The URL for Content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementPostProductMapping',
            fields=[
                ('engagement_post_product_mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'engagement_post_product_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfluencerMaster',
            fields=[
                ('influencer_master_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_pic_url', models.CharField(blank=True, max_length=200, null=True)),
                ('sample_video_url', models.CharField(blank=True, max_length=200, null=True)),
                ('sample_video1_url', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('highlight_text', models.CharField(blank=True, null=True)),
                ('hash_tags', models.CharField(blank=True, max_length=300, null=True)),
                ('sample_video2_url', models.CharField(blank=True, max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, null=True)),
                ('folder_name', models.CharField(blank=True, max_length=24, null=True)),
                ('is_master_account', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'influencer_master',
                'managed': False,
            },
        ),
    ]
