# Generated by Django 5.0.6 on 2024-11-05 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'collection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EngagementPostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('sku', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'engagement_post_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EngagementPostCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_seconds', models.IntegerField()),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='engagement.collection')),
                ('engagement_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='engagement.engagementpostproduct')),
            ],
            options={
                'db_table': 'engagement_post_collection',
                'managed': True,
            },
        ),
    ]
