# Generated by Django 5.0.6 on 2024-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_collection_engagementpostproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementpostcollection',
            name='duration_in_seconds',
            field=models.IntegerField(default=1),
        ),
    ]
